// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Tunr.Models;

namespace Tunr.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<Guid>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Tunr.Models.Library.Track", b =>
                {
                    b.Property<string>("TagTitle")
                        .ValueGeneratedOnAdd();

                    b.Property<short>("AudioBitrateKbps");

                    b.Property<byte>("AudioChannels");

                    b.Property<short>("AudioDurationSeconds");

                    b.Property<int>("AudioSampleRateHz");

                    b.Property<string>("FileExtension");

                    b.Property<string>("FileName");

                    b.Property<string>("FileRelativePath");

                    b.Property<byte[]>("FileSha256Hash");

                    b.Property<int>("FileSizeBytes");

                    b.Property<long>("LibraryDateTimeAdded");

                    b.Property<long>("LibraryDateTimeModified");

                    b.Property<int>("LibraryPlays");

                    b.Property<byte>("LibraryRating");

                    b.Property<long>("StorageLocation");

                    b.Property<string>("TagAlbum");

                    b.Property<string>("TagAlbumArtist");

                    b.Property<short>("TagAlbumDiscCount");

                    b.Property<short>("TagAlbumTrackCount");

                    b.Property<short>("TagBeatsPerMinute");

                    b.Property<string>("TagComment");

                    b.Property<short>("TagDiscNumber");

                    b.Property<short>("TagTrackNumber");

                    b.Property<short>("TagYear");

                    b.Property<Guid>("TrackId");

                    b.Property<Guid>("UserId");

                    b.HasKey("TagTitle")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("UserId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Tunr.Models.Library.TrackComposer", b =>
                {
                    b.Property<Guid>("TrackId");

                    b.Property<string>("Composer");

                    b.HasKey("TrackId", "Composer");

                    b.ToTable("TrackComposers");
                });

            modelBuilder.Entity("Tunr.Models.Library.TrackGenre", b =>
                {
                    b.Property<Guid>("TrackId");

                    b.Property<string>("Genre");

                    b.HasKey("TrackId", "Genre");

                    b.ToTable("TrackGenres");
                });

            modelBuilder.Entity("Tunr.Models.Library.TrackPerformer", b =>
                {
                    b.Property<Guid>("TrackId");

                    b.Property<string>("Performer");

                    b.HasKey("TrackId", "Performer");

                    b.ToTable("TrackPerformers");
                });

            modelBuilder.Entity("Tunr.Models.TunrRole", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<Guid>("Id");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Name")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Tunr.Models.TunrUser", b =>
                {
                    b.Property<string>("UserName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256);

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<Guid>("Id");

                    b.Property<long>("LibraryOffset");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.HasKey("UserName")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Tunr.Models.TunrRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Tunr.Models.TunrUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Tunr.Models.TunrUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Tunr.Models.TunrRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Tunr.Models.TunrUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Tunr.Models.TunrUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Tunr.Models.Library.Track", b =>
                {
                    b.HasOne("Tunr.Models.TunrUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Tunr.Models.Library.TrackComposer", b =>
                {
                    b.HasOne("Tunr.Models.Library.Track", "Track")
                        .WithMany("DbTagComposers")
                        .HasForeignKey("TrackId")
                        .HasPrincipalKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Tunr.Models.Library.TrackGenre", b =>
                {
                    b.HasOne("Tunr.Models.Library.Track", "Track")
                        .WithMany("DbTagGenres")
                        .HasForeignKey("TrackId")
                        .HasPrincipalKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Tunr.Models.Library.TrackPerformer", b =>
                {
                    b.HasOne("Tunr.Models.Library.Track", "Track")
                        .WithMany("DbTagPerformers")
                        .HasForeignKey("TrackId")
                        .HasPrincipalKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
